export function adminPage(siteKeyRaw: string): string {
  const siteKey = siteKeyRaw.replace(/"/g, '&quot;');
  return `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CleanC License Server</title>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
<style>
*{box-sizing:border-box}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17233b;background:radial-gradient(circle at 5% 8%,#d9efff,transparent 34%),radial-gradient(circle at 92% 4%,#eadfff,transparent 38%),linear-gradient(135deg,#f8fbff,#eef4ff);min-height:100vh}.glass{background:rgba(255,255,255,.64);backdrop-filter:blur(28px) saturate(150%);border:1px solid rgba(255,255,255,.85);box-shadow:0 24px 70px rgba(43,72,140,.14),inset 0 1px 0 #fff;border-radius:28px}.login{width:min(430px,calc(100% - 32px));padding:34px;position:absolute;left:50%;top:50%;transform:translate(-50%,-50%)}.logo{width:56px;height:56px;border-radius:18px;display:grid;place-items:center;font-size:26px;font-weight:800;color:#fff;background:linear-gradient(145deg,#4a8cff,#765cff)}.muted{color:#72809a}.app{display:none;min-height:100vh;padding:20px}.side{position:fixed;top:20px;bottom:20px;width:230px;padding:22px}.main{margin-left:250px}.nav button{display:block;width:100%;text-align:left;margin:7px 0;background:transparent;color:#58667e}.nav button.active{background:#ffffffcf;color:#315fc5}.btn{border:0;border-radius:14px;padding:11px 15px;cursor:pointer;font-weight:650}.primary{background:linear-gradient(135deg,#4d88ff,#735cff);color:#fff}.danger{background:#fff0f2;color:#c73555}.secondary{background:#eef3ff;color:#375baf}.disabled{opacity:.5;cursor:not-allowed}input,select,button{font:inherit}input,select{width:100%;padding:12px 14px;border:1px solid #dce5f4;border-radius:14px;background:#ffffffdf}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.row .btn{flex:0 0 auto}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.card,.panel{padding:20px}.panel{margin-top:16px}.stat b{font-size:30px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #e4eaf3;vertical-align:top}code{background:#eef3ff;padding:3px 6px;border-radius:7px;word-break:break-all}.section{display:none}.section.active{display:block}.hidden{display:none!important}.notice{padding:12px 14px;border-radius:14px;background:#fff8dd;color:#705400;margin:12px 0}.ok{color:#26844a}.bad{color:#b83250}.warn{color:#a66a00}@media(max-width:1050px){.grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.side{position:static;width:auto;margin-bottom:14px}.main{margin-left:0}.grid{grid-template-columns:repeat(2,1fr)}.app{padding:12px}}@media(max-width:560px){.grid{grid-template-columns:1fr}.row>*{flex-basis:100%}}
</style>
</head><body>
<div id="login" class="login glass"><div class="logo">C</div><h1>CleanC License</h1><p class="muted">管理员控制台</p><input id="password" type="password" autocomplete="current-password" placeholder="管理员密码"><div style="height:14px"></div><div id="loginTs" class="cf-turnstile" data-sitekey="${siteKey}"></div><div style="height:14px"></div><button class="btn primary" style="width:100%" onclick="doLogin()">登录</button><p id="loginMsg" class="muted"></p></div>
<div id="app" class="app"><aside class="side glass"><div class="row"><div class="logo" style="width:42px;height:42px;font-size:20px">C</div><b>CleanC</b></div><div class="nav" style="margin-top:22px"><button class="btn active" data-tab="dashboard">仪表盘</button><button class="btn" data-tab="licenses">授权管理</button><button class="btn" data-tab="devices">设备管理</button><button class="btn" data-tab="logs">操作日志</button><button class="btn" data-tab="settings">设置</button></div><div style="position:absolute;left:22px;right:22px;bottom:22px"><button class="btn secondary" style="width:100%" onclick="logout()">退出登录</button></div></aside>
<main class="main"><h2 id="title">仪表盘</h2><p class="muted">CleanC 授权服务管理中心</p>
<section id="dashboard" class="section active"><div class="grid"><div class="card glass stat">总授权<br><b id="sTotal">-</b></div><div class="card glass stat">当前有效<br><b id="sActive">-</b></div><div class="card glass stat">已过期<br><b id="sExpired">-</b></div><div class="card glass stat">已禁用<br><b id="sDisabled">-</b></div><div class="card glass stat">绑定设备<br><b id="sDevices">-</b></div></div></section>
<section id="licenses" class="section"><div class="panel glass"><div class="notice"><b>时长授权规则：</b>例如创建 7 天授权，创建后不会开始倒计时；第一次设备成功激活时才开始计算 7×24 小时。之后重复激活、解绑重绑、禁用恢复都不会重新计时或延长有效期。批量生成一次最多 15 个。</div><div class="row"><input id="customKey" placeholder="自定义授权码（留空随机）"><select id="licenseType" onchange="licenseTypeChanged()"><option value="permanent">永久</option><option value="duration">激活后 N 天</option><option value="fixed">固定到期</option></select><input id="durationDays" type="number" value="365" min="1" max="36500" placeholder="有效天数"><input id="expiresAt" class="hidden" type="datetime-local"><input id="maxDevices" type="number" value="1" min="1" max="1000" placeholder="设备数"><input id="batchCount" type="number" value="1" min="1" max="15" placeholder="生成数量"><button class="btn primary" onclick="createLicense()">生成授权</button></div><div style="height:10px"></div><input id="licenseNote" placeholder="备注（可选）"></div><div class="panel glass" style="overflow:auto"><table><thead><tr><th>授权码</th><th>状态</th><th>类型</th><th>首次激活</th><th>到期</th><th>设备</th><th>创建</th><th>操作</th></tr></thead><tbody id="licenseRows"></tbody></table></div></section>
<section id="devices" class="section"><div class="panel glass" style="overflow:auto"><table><thead><tr><th>设备</th><th>授权码</th><th>Windows</th><th>App</th><th>最近在线</th><th>状态</th><th>操作</th></tr></thead><tbody id="deviceRows"></tbody></table></div></section>
<section id="logs" class="section"><div class="panel glass" style="overflow:auto"><table><thead><tr><th>时间</th><th>事件</th><th>IP</th><th>详情</th></tr></thead><tbody id="logRows"></tbody></table></div></section>
<section id="settings" class="section"><div class="panel glass"><h3>域名与 API</h3><p>当前访问：<code id="currentOrigin">-</code></p><p>Bootstrap：<code id="bootstrapUrl">-</code></p><p>主授权地址：<code id="canonicalUrl">-</code></p><div class="notice">先在 Cloudflare Pages 项目的 Custom domains 中绑定正式域名，并把该主机名加入 Turnstile Hostname Management，再在这里保存。系统会验证目标域名确实指向 CleanC 服务。</div><div class="row"><input id="newDomain" placeholder="license.example.com"><input id="confirmPassword" type="password" placeholder="管理员密码"></div><div style="height:12px"></div><div id="settingsTs" class="cf-turnstile" data-sitekey="${siteKey}"></div><div style="height:12px"></div><button class="btn primary" onclick="saveDomain()">检测并保存</button> <button class="btn danger" onclick="rollbackDomain()">恢复 Bootstrap 地址</button></div><div class="panel glass"><h3>API 地址</h3><div id="apiList"></div></div></section>
</main></div>
<script>
var csrf='';
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function isExpired(x){return !!x.expires_at&&new Date(x.expires_at).getTime()<=Date.now()}
function statusText(x){if(isExpired(x))return '已过期';if(x.status==='disabled')return '已禁用';if(x.license_type==='duration'&&!x.activated_at)return '未激活';return '有效'}
function statusClass(x){if(isExpired(x))return 'bad';if(x.status==='disabled')return 'warn';if(x.license_type==='duration'&&!x.activated_at)return 'muted';return 'ok'}
function typeText(x){if(x.license_type==='permanent')return '永久';if(x.license_type==='duration')return '激活后 '+x.duration_days+' 天';if(x.license_type==='fixed')return '固定到期';return x.license_type}
function expiryText(x){if(x.license_type==='permanent')return '永久';if(x.license_type==='duration'&&!x.activated_at)return '未开始（激活后 '+x.duration_days+' 天）';return x.expires_at||'-'}
function actionHtml(x){if(isExpired(x))return '-';var action=x.status==='active'?'disable':'enable';var text=x.status==='active'?'禁用':'恢复';return '<button class="btn secondary" onclick="toggleLic(\''+esc(x.id)+'\',\''+action+'\')">'+text+'</button>'}
async function call(path,opt){opt=opt||{};opt.headers=Object.assign({},opt.headers||{}, {'content-type':'application/json','x-csrf-token':csrf});var r=await fetch(path,opt);var j;try{j=await r.json()}catch(e){j={success:false,message:'服务器返回格式异常'}}if(!r.ok&&j.success!==false)j.success=false;return j}
async function boot(){var r=await fetch('/admin/api/session',{cache:'no-store'});if(!r.ok)return;var j=await r.json();csrf=j.csrfToken;q('login').style.display='none';q('app').style.display='block';loadDashboard()}
async function doLogin(){var token=q('loginTs').querySelector('[name="cf-turnstile-response"]')?.value||'';var r=await call('/admin/api/login',{method:'POST',body:JSON.stringify({password:q('password').value,turnstileToken:token})});if(r.success)location.reload();else{q('loginMsg').textContent=r.message||'登录失败';if(window.turnstile)turnstile.reset(q('loginTs'))}}
async function logout(){var r=await call('/admin/api/logout',{method:'POST',body:'{}'});if(r.success)location.reload()}
async function loadDashboard(){var r=await call('/admin/api/dashboard');if(r.success){q('sTotal').textContent=r.stats.total;q('sActive').textContent=r.stats.active;q('sExpired').textContent=r.stats.expired;q('sDisabled').textContent=r.stats.disabled;q('sDevices').textContent=r.stats.devices}}
function licenseTypeChanged(){var t=q('licenseType').value;q('durationDays').classList.toggle('hidden',t!=='duration');q('expiresAt').classList.toggle('hidden',t!=='fixed')}
async function loadLicenses(){var r=await call('/admin/api/licenses');if(!r.success){alert(r.message||'授权列表加载失败');return}q('licenseRows').innerHTML=(r.licenses||[]).map(function(x){return '<tr><td><code>'+esc(x.license_key)+'</code></td><td class="'+statusClass(x)+'">'+esc(statusText(x))+'</td><td>'+esc(typeText(x))+'</td><td>'+esc(x.activated_at||'-')+'</td><td>'+esc(expiryText(x))+'</td><td>'+Number(x.device_count||0)+'/'+Number(x.max_devices||0)+'</td><td>'+esc((x.created_at||'').slice(0,10))+'</td><td>'+actionHtml(x)+'</td></tr>'}).join('')}
async function createLicense(){var fixed=q('expiresAt').value;var r=await call('/admin/api/licenses',{method:'POST',body:JSON.stringify({licenseKey:q('customKey').value,licenseType:q('licenseType').value,durationDays:+q('durationDays').value,expiresAt:fixed?new Date(fixed).toISOString():null,maxDevices:+q('maxDevices').value,count:+q('batchCount').value,note:q('licenseNote').value})});if(r.success){alert('已生成 '+r.licenseKeys.length+' 个授权码\n'+r.licenseKeys.join('\n'));loadLicenses();loadDashboard()}else alert(r.message||r.code||'生成失败')}
async function toggleLic(i,o){var r=await call('/admin/api/licenses/'+encodeURIComponent(i)+'/'+o,{method:'POST',body:'{}'});if(!r.success)alert(r.message||'操作失败');loadLicenses();loadDashboard()}
async function loadDevices(){var r=await call('/admin/api/devices');if(!r.success)return;q('deviceRows').innerHTML=(r.devices||[]).map(function(x){return '<tr><td>'+esc(x.device_name||x.device_id)+'</td><td><code>'+esc(x.license_key)+'</code></td><td>'+esc(x.windows_version)+'</td><td>'+esc(x.app_version)+'</td><td>'+esc(x.last_seen_at)+'</td><td>'+(x.revoked_at?'已解绑':'已绑定')+'</td><td>'+(x.revoked_at?'-':'<button class="btn danger" onclick="revokeDevice(\''+esc(x.id)+'\')">解绑</button>')+'</td></tr>'}).join('')}
async function revokeDevice(i){if(confirm('确认解绑此设备？解绑会释放设备名额，但不会重置授权首次激活时间或延长到期时间。')){var r=await call('/admin/api/devices/'+encodeURIComponent(i)+'/revoke',{method:'POST',body:'{}'});if(!r.success)alert(r.message||'解绑失败');loadDevices();loadDashboard()}}
async function loadLogs(){var r=await call('/admin/api/logs');if(!r.success)return;q('logRows').innerHTML=(r.logs||[]).map(function(x){return '<tr><td>'+esc(x.created_at)+'</td><td>'+esc(x.event_type)+'</td><td>'+esc(x.ip)+'</td><td><code>'+esc(x.detail)+'</code></td></tr>'}).join('')}
async function loadSettings(){var r=await call('/admin/api/settings');if(!r.success)return;q('currentOrigin').textContent=r.currentOrigin;q('canonicalUrl').textContent=r.canonicalBaseUrl;q('bootstrapUrl').textContent=r.bootstrapBaseUrl+'/bootstrap/v1/config';var e=['/api/v1/license/activate','/api/v1/license/validate','/api/v1/license/refresh','/api/v1/device/challenge','/api/v1/device/verify','/api/v1/health','/api/v1/meta'];q('apiList').innerHTML=e.map(function(x){return '<p><code>'+esc(r.canonicalBaseUrl+x)+'</code></p>'}).join('')}
function settingsToken(){return q('settingsTs').querySelector('[name="cf-turnstile-response"]')?.value||''}
async function saveDomain(){var r=await call('/admin/api/settings/domain',{method:'POST',body:JSON.stringify({baseUrl:q('newDomain').value,password:q('confirmPassword').value,turnstileToken:settingsToken()})});alert(r.success?'主授权域名已更新':(r.message||r.code||'保存失败'));if(r.success)loadSettings();if(window.turnstile)turnstile.reset(q('settingsTs'))}
async function rollbackDomain(){var r=await call('/admin/api/settings/domain/rollback',{method:'POST',body:JSON.stringify({password:q('confirmPassword').value,turnstileToken:settingsToken()})});alert(r.success?'已恢复 Bootstrap 地址':(r.message||'验证失败'));if(r.success)loadSettings();if(window.turnstile)turnstile.reset(q('settingsTs'))}
document.querySelectorAll('.nav button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.nav button').forEach(function(x){x.classList.remove('active')});document.querySelectorAll('.section').forEach(function(x){x.classList.remove('active')});b.classList.add('active');q(b.dataset.tab).classList.add('active');q('title').textContent=b.textContent;if(b.dataset.tab==='dashboard')loadDashboard();if(b.dataset.tab==='licenses')loadLicenses();if(b.dataset.tab==='devices')loadDevices();if(b.dataset.tab==='logs')loadLogs();if(b.dataset.tab==='settings')loadSettings()}});
licenseTypeChanged();boot();
</script></body></html>`;
}
